title: How to dismantle a Peakboard Box
description: "Blog about how to dismantle a Peakboard Box"
baseurl: ""
url: "https://how-to-dismantle-a-peakboard-box.com"
permalink: /:title:output_ext
port: 4001

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Portions of text found throughout common components (like the footer) can be configured here for each language
content:
  link-back-to-home: 'back to home'
  side-menu-home: 'Home'
  side-menu-about: 'About'
  side-menu-title: 'What is this blog?'
  side-menu-text: 'How to dismantle a Peakboard Box is a blog about various tips, tricks and hacks for Peakboard Boxes.'
  side-menu-categories: 'Categories'
  side-menu-date: 'Archive'
  side-menu-date-all: 'Show all posts'
  side-menu-contact-title: 'Contact'
  side-menu-contact-text: 'If you have any questions, feel free to contact us at info@how-to-dismantle-a-peakboard-box.com'

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js